### ISSUE TITLE
Proposal of 6 improvements/features to enhance usability.

### ISSUE THREAD

**Issue by sfk26** [Zimzozaur/FocusKeeper-TUI#1]
**A nice app for studying and working!**

I would like to see some features that could make it more useful:

1. The ability to set a certain number of sessions and breaks, for example three 50-minute sessions and three 10-minute breaks for 3 hours of work in total.
2. Session history.
3. Customizable tags and presets that can save session queues, alarms, and ambient sounds.
4. More available basic sounds.
5. Option to share your sessions with friends and follow each other's progress.
6. Different themes and ways to personalize the app.

**Good luck!**

**Comment by Zimzozaur** [comment]
Can you create new issues to separate the features?

1. Will be added in v1 (new issue)
2. Will be added in v1, and we already have a DB that collects sessions (new issue)
3. I would merge it with 1 because for me, it is just a 1 with extra customization. 
4. Do you mean more default build in songs?
5. Social features will be added after release of a fully working timer in offline mode (new issue)
6. Will be added in v1 and I have cool ideas that I think you will enjoy (new issue)

**Comment by Zimzozaur** [comment]
I'm closing this issue because it has been divided into smaller, more specific issues. Please refer to (#2, #3, #5, #6) for further details.
