### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by sfk26** [Zimzozaur/FocusKeeper-TUI#4]
More default sounds to give users a choice. Because not many people would like to search for a sound which is good for them and upload it to the app. A wider selection makes things easier.

**Comment by Zimzozaur** [comment]
I agree. I want Focus Keeper to have a rich default library, but to achieve this, I need to find good sounds under an open license, purchase them, or rely on community members to share their sounds under an open license.

I'm going to close this issue since it's not tech-related. As the community grows, we'll find a way to make the app sound great.
